### ISSUE TITLE
Duplicate keys in sheepdog deployment yaml

### ISSUE THREAD

**Issue by krumware** [uc-cdis/gen3-helm#78]
There is a duplicate env var key in helm/sheepdog/templates/deployment.yaml which is causing template rendering issues

error:
```
W0104 17:44:04.431345    8988 warnings.go:70] spec.template.spec.containers[0].env[15].name: duplicate name "FENCE_URL"
```

snippet:
```yaml
            - name: FENCE_URL
              valueFrom:
                configMapKeyRef:
                  name: manifest-global
                  key: fence_url
                  optional: true
            - name: INDEXD_PASS
              valueFrom:
                secretKeyRef:
                  name: indexd-service-creds
                  key: gdcapi
                  optional: false
            - name: GEN3_UWSGI_TIMEOUT
              value: "600"
            - name: DICTIONARY_URL
              value: {{ include "sheepdog.dictionaryUrl" .}}
            {{- with .Values.indexdUrl }}
            - name: INDEX_CLIENT_HOST
              value: {{ . }}
            {{- end }}
            {{- with .Values.fenceUrl }}
            - name: FENCE_URL
              value: {{ . }}
            {{- end }}
```

**Comment by krumware** [comment]
It looks like, in gen3/templates/global-manifest.yaml that fence_url is not an included key.
If that's the case, the configmap reference would likely need to be removed, and the direct env kept.

Although, there are multiple references to 
```
- name: FENCE_URL
              valueFrom:
                configMapKeyRef:
                  name: manifest-global
                  key: fence_url
                  optional: true
```
in other templates.
Should fence_url be added to the global-manifest.yaml?
