### ISSUE TITLE
Duplicate key terminationGracePeriodSeconds in wts deployment

### ISSUE THREAD

**Issue by krumware** [uc-cdis/gen3-helm#79]
terminationGracePeriodSeconds is duplicated in wts/templates/deployment.yaml

snippet:
```
      terminationGracePeriodSeconds: 10
      volumes:
        - name: wts-secret
          secret:
            secretName: "wts-g3auto"
      terminationGracePeriodSeconds: 10
```
